# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np

df = pd.read_csv("Hospital_Data.csv")

# تنظيف الأعمدة
df.columns = df.columns.str.replace(' ', '_')
df.drop_duplicates(inplace=True)

# نصوص
text_cols = ["Hospital_Name", "Location", "Department"]
for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

# أرقام
numeric_cols = ["Doctors_Count", "Patients_Count", "Medical_Expenses"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# تواريخ
date_cols = ["Admission_Date", "Discharge_Date"]
for col in date_cols:
    df[col] = pd.to_datetime(df[col], dayfirst=True, errors="coerce")

# إزالة القيم غير المنطقية
for col in numeric_cols:
    df.loc[df[col] < 0, col] = np.nan

# مدة الإقامة
df["Stay_Days"] = (df["Discharge_Date"] - df["Admission_Date"]).dt.days

# تكلفة لكل مريض (مهم جدًا)
df["Cost_per_Patient"] = df["Medical_Expenses"] / df["Patients_Count"]

# استخراج الشهر والسنة
df["Year"] = df["Admission_Date"].dt.year
df["Month"] = df["Admission_Date"].dt.month

data = df[[
    "Doctors_Count",
    "Patients_Count",
    "Stay_Days",
    "Department",
    "Location",
    "Medical_Expenses"
]].dropna()

from sklearn.preprocessing import OneHotEncoder

data = pd.get_dummies(data, columns=["Department", "Location"], drop_first=True)

from sklearn.model_selection import train_test_split

X = data.drop("Medical_Expenses", axis=1)
y = data["Medical_Expenses"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

model = Pipeline([
    ("rf", RandomForestRegressor(
        n_estimators=200,
        max_depth=10,
        random_state=42
    ))
])

model.fit(X_train, y_train)

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

model = Pipeline([
    ("rf", RandomForestRegressor(
        n_estimators=200,
        max_depth=10,
        random_state=42
    ))
])

model.fit(X_train, y_train)

from sklearn.metrics import r2_score, mean_absolute_error

y_pred = model.predict(X_test)

print("📊 Model Performance:")
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

from sklearn.model_selection import GridSearchCV

param_grid = {
    "rf__n_estimators": [100, 200],
    "rf__max_depth": [5, 10, 15]
}

grid = GridSearchCV(model, param_grid, cv=3, n_jobs=-1)
grid.fit(X_train, y_train)

print("🔥 Best Params:", grid.best_params_)

best_model = grid.best_estimator_

importances = best_model.named_steps["rf"].feature_importances_

feat_imp = pd.Series(importances, index=X.columns).sort_values(ascending=False)

print(feat_imp.head(10))
feat_imp.head(10).plot(kind='barh')

from google.colab import files
data["Predicted_Expenses"] = model.predict(X)
data.to_csv("predictions.csv", index=False)

files.download("predictions.csv")